// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Online_Art_Gallery_and_Studio_Reservation_System.Data;

#nullable disable

namespace Online_Art_Gallery_and_Studio_Reservation_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"));

                    b.Property<string>("Biography")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Artwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtworkId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("ArtworkCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("ArtworkId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("ArtworkCategoryId");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ArtworkCategory", b =>
                {
                    b.Property<int>("ArtworkCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtworkCategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArtworkCategoryId");

                    b.ToTable("ArtworkCategories");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ArtworkComparisonItem", b =>
                {
                    b.Property<int>("ArtworkComparisonItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtworkComparisonItemId"));

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<int>("ComparisonSessionId")
                        .HasColumnType("int");

                    b.HasKey("ArtworkComparisonItemId");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("ComparisonSessionId", "ArtworkId")
                        .IsUnique();

                    b.ToTable("ArtworkComparisonItems");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ArtworkFavorite", b =>
                {
                    b.Property<int>("ArtworkFavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtworkFavoriteId"));

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ArtworkFavoriteId");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("UserId", "ArtworkId")
                        .IsUnique();

                    b.ToTable("ArtworkFavorites");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ArtworkImage", b =>
                {
                    b.Property<int>("ArtworkImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtworkImageId"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("ArtworkImageId");

                    b.HasIndex("ArtworkId");

                    b.ToTable("ArtworkImages");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ArtworkViewLog", b =>
                {
                    b.Property<int>("ArtworkViewLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtworkViewLogId"));

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViewerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ArtworkViewLogId");

                    b.HasIndex("ViewerId");

                    b.HasIndex("ArtworkId", "ViewedAt");

                    b.ToTable("ArtworkViewLogs");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Campaign", b =>
                {
                    b.Property<int>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampaignId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CampaignId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ComparisonSession", b =>
                {
                    b.Property<int>("ComparisonSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComparisonSessionId"));

                    b.Property<int>("ComparisonType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("bit");

                    b.Property<string>("SavedName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ComparisonSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("ComparisonSessions");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxUsageCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("CouponId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.CouponRedemption", b =>
                {
                    b.Property<int>("CouponRedemptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponRedemptionId"));

                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CouponRedemptionId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.HasIndex("CouponId", "UserId", "OrderId");

                    b.ToTable("CouponRedemptions");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("CouponId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("OrderId", "ArtworkId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkshopScheduleId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("WorkshopScheduleId");

                    b.HasIndex("UserId", "WorkshopScheduleId", "Status");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int?>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerifiedPurchaseOrParticipation")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WorkshopEventId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("WorkshopEventId");

                    b.HasIndex("UserId", "TargetType", "ArtworkId", "WorkshopEventId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating_Between_1_5", "[Rating] >= 1 AND [Rating] <= 5");

                            t.HasCheckConstraint("CK_Review_Target_NotNull", "([ArtworkId] IS NOT NULL AND [WorkshopEventId] IS NULL) OR ([ArtworkId] IS NULL AND [WorkshopEventId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ReviewHelpfulVote", b =>
                {
                    b.Property<int>("ReviewHelpfulVoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewHelpfulVoteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHelpful")
                        .HasColumnType("bit");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewHelpfulVoteId");

                    b.HasIndex("UserId");

                    b.HasIndex("ReviewId", "UserId")
                        .IsUnique();

                    b.ToTable("ReviewHelpfulVotes");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ReviewResponse", b =>
                {
                    b.Property<int>("ReviewResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewResponseId"));

                    b.Property<string>("AdminUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("ReviewResponseId");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewResponses");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.SupportMessage", b =>
                {
                    b.Property<int>("SupportMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportMessageId"));

                    b.Property<bool>("IsFromAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupportTicketId")
                        .HasColumnType("int");

                    b.HasKey("SupportMessageId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("SupportTicketId");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.SupportTicket", b =>
                {
                    b.Property<int>("SupportTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportTicketId"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SupportTicketId");

                    b.HasIndex("UserId", "Status", "CreatedAt");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopCategory", b =>
                {
                    b.Property<int>("WorkshopCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkshopCategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WorkshopCategoryId");

                    b.ToTable("WorkshopCategories");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopComparisonItem", b =>
                {
                    b.Property<int>("WorkshopComparisonItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkshopComparisonItemId"));

                    b.Property<int>("ComparisonSessionId")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopEventId")
                        .HasColumnType("int");

                    b.HasKey("WorkshopComparisonItemId");

                    b.HasIndex("WorkshopEventId");

                    b.HasIndex("ComparisonSessionId", "WorkshopEventId")
                        .IsUnique();

                    b.ToTable("WorkshopComparisonItems");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopEvent", b =>
                {
                    b.Property<int>("WorkshopEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkshopEventId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("WorkshopCategoryId")
                        .HasColumnType("int");

                    b.HasKey("WorkshopEventId");

                    b.HasIndex("WorkshopCategoryId");

                    b.ToTable("WorkshopEvents");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopSchedule", b =>
                {
                    b.Property<int>("WorkshopScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkshopScheduleId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkshopEventId")
                        .HasColumnType("int");

                    b.HasKey("WorkshopScheduleId");

                    b.HasIndex("WorkshopEventId", "StartDateTime", "EndDateTime");

                    b.ToTable("WorkshopSchedules");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Artwork", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Artist", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ArtworkCategory", "ArtworkCategory")
                        .WithMany("Artworks")
                        .HasForeignKey("ArtworkCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("ArtworkCategory");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ArtworkComparisonItem", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Artwork", "Artwork")
                        .WithMany("ComparisonItems")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ComparisonSession", "ComparisonSession")
                        .WithMany("ArtworkItems")
                        .HasForeignKey("ComparisonSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("ComparisonSession");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ArtworkFavorite", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Artwork", "Artwork")
                        .WithMany("Favorites")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", "User")
                        .WithMany("FavoriteArtworks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ArtworkImage", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Artwork", "Artwork")
                        .WithMany("Images")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ArtworkViewLog", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Artwork", "Artwork")
                        .WithMany("ViewLogs")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", "Viewer")
                        .WithMany()
                        .HasForeignKey("ViewerId");

                    b.Navigation("Artwork");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ComparisonSession", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", "User")
                        .WithMany("ComparisonSessions")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.CouponRedemption", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Coupon", "Coupon")
                        .WithMany("Redemptions")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", "User")
                        .WithMany("CouponRedemptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Order", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Coupon", "Coupon")
                        .WithMany("Orders")
                        .HasForeignKey("CouponId");

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.OrderItem", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Artwork", "Artwork")
                        .WithMany("OrderItems")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Payment", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Reservation", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopSchedule", "WorkshopSchedule")
                        .WithMany("Reservations")
                        .HasForeignKey("WorkshopScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkshopSchedule");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Review", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Artwork", "Artwork")
                        .WithMany("Reviews")
                        .HasForeignKey("ArtworkId");

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopEvent", "WorkshopEvent")
                        .WithMany("Reviews")
                        .HasForeignKey("WorkshopEventId");

                    b.Navigation("Artwork");

                    b.Navigation("User");

                    b.Navigation("WorkshopEvent");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ReviewHelpfulVote", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Review", "Review")
                        .WithMany("HelpfulVotes")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", "User")
                        .WithMany("ReviewHelpfulVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ReviewResponse", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", "AdminUser")
                        .WithMany("ReviewResponses")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.Review", "Review")
                        .WithMany("Responses")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.SupportMessage", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", "Sender")
                        .WithMany("SupportMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.SupportTicket", "SupportTicket")
                        .WithMany("Messages")
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.SupportTicket", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopComparisonItem", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.ComparisonSession", "ComparisonSession")
                        .WithMany("WorkshopItems")
                        .HasForeignKey("ComparisonSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopEvent", "WorkshopEvent")
                        .WithMany("ComparisonItems")
                        .HasForeignKey("WorkshopEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComparisonSession");

                    b.Navigation("WorkshopEvent");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopEvent", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopCategory", "WorkshopCategory")
                        .WithMany("WorkshopEvents")
                        .HasForeignKey("WorkshopCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkshopCategory");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopSchedule", b =>
                {
                    b.HasOne("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopEvent", "WorkshopEvent")
                        .WithMany("Schedules")
                        .HasForeignKey("WorkshopEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkshopEvent");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ApplicationUser", b =>
                {
                    b.Navigation("ComparisonSessions");

                    b.Navigation("CouponRedemptions");

                    b.Navigation("FavoriteArtworks");

                    b.Navigation("Orders");

                    b.Navigation("Reservations");

                    b.Navigation("ReviewHelpfulVotes");

                    b.Navigation("ReviewResponses");

                    b.Navigation("Reviews");

                    b.Navigation("SupportMessages");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Artist", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Artwork", b =>
                {
                    b.Navigation("ComparisonItems");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");

                    b.Navigation("ViewLogs");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ArtworkCategory", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.ComparisonSession", b =>
                {
                    b.Navigation("ArtworkItems");

                    b.Navigation("WorkshopItems");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Coupon", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.Review", b =>
                {
                    b.Navigation("HelpfulVotes");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopCategory", b =>
                {
                    b.Navigation("WorkshopEvents");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopEvent", b =>
                {
                    b.Navigation("ComparisonItems");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Online_Art_Gallery_and_Studio_Reservation_System.Models.WorkshopSchedule", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
